### ISSUE TITLE
Does not work on Windows

### ISSUE THREAD

**Issue by Vertexwahn** [justusc/FindTBB#1]
Did you test this with a Windows environment?

**Comment by justusc** [comment]
The code for library names and paths are incomplete for Windows platforms. I can take a look at it this weekend if you want to use this module. What version of Windows and toolchain are you using?

I simply had not implemented the code necessary for Windows since do not own a Windows box and no one had shown any interest in it for Windows platforms.

**Comment by justusc** [comment]
Also, pull requests are welcome. ;-)

**Comment by Vertexwahn** [comment]
I am using Windows 10, Visual Studio 2015, Targeting x64. I also tested https://raw.githubusercontent.com/HSA-Libraries/Bolt/master/examples/FindTBB.cmake but it finds the wrong libs:
`C:/thirdparty/tbb44_20151115oss/lib/ia32/vc11/tbbmalloc.lib`

**Comment by justusc** [comment]
OK, I will look into making the necessary changes this weekend or early next week.

**Comment by Vertexwahn** [comment]
I started to make a quick&dirty fix for my project: https://bitbucket.org/Vertexwahn/cmakedemos/src/4ba00a875232ea6ba2a3b27e5e872a6ed6e34a76/ThreadBuildingBlocks/cmake/FindTBB.cmake?at=default&fileviewer=file-view-default
Works only for VS2015 + x64 - but it should not be too difficult to adapt it for other version of Visual Studio

**Comment by justusc** [comment]
I pushed some changes that _should_ correctly detect the TBB on Windows platforms. Unfortunately, I was not able to test it since I do not have Windows setup on my computer. Please give it a try and let me know how it goes.
