### ISSUE TITLE
TBB_LIBRARIES only contains debug libs

### ISSUE THREAD

**Issue by caron** [justusc/FindTBB#4]
Thanks for this great module to find TBB...

TBB_LIBRARIES seems to only contain the debug libs?

```
TBB FOUND: TRUE
TBB VERSION: 4.4
TBB LIBRARIES: E:/library/development/tbb/tbb44_20160526oss/lib/intel64/vc14/tbb_preview_debug.libE:/library/development/tbb/tbb44_20160526oss/lib/intel64/vc14/tbbmalloc_debug.libE:/library/development/tbb/tbb44_20160526oss/lib/intel64/vc14/tbb_debug.lib
```

I haven't set to use TBB_USE_DEBUG_BUILD but CMake is configuring a Debug build option (along with Release) and that seems to trigger this conditional to never get to the release built components.

```
# Set the library to be used for the component
if(NOT TBB_${_comp}_LIBRARY)
   if(TBB_USE_DEBUG_BUILD AND TBB_${_comp}_LIBRARY_DEBUG)
     set(TBB_${_comp}_LIBRARY "${TBB_${_comp}_LIBRARY_DEBUG}")
   elseif(TBB_${_comp}_LIBRARY_RELEASE)
     set(TBB_${_comp}_LIBRARY "${TBB_${_comp}_LIBRARY_RELEASE}")
   elseif(TBB_${_comp}_LIBRARY_DEBUG)
     set(TBB_${_comp}_LIBRARY "${TBB_${_comp}_LIBRARY_DEBUG}")
   endif()
endif()
```

**Comment by caron** [comment]
So if I set TBB_USE_DEBUG_BUILD=0 I get the right result but should this be the default behavior? I mean shouldn't we get release libs if the variable isn't defined and if it is set to 0?

**Comment by justusc** [comment]
@caron Thanks. I am glad you found it useful.

The default behavior of the module is to use the TBB debug build if `CMAKE_BUILD_TYPE` is set to `Debug` or `RelWithDebInfo`. Otherwise it will choose the release build of TBB. You can see this logic here: https://github.com/justusc/FindTBB/blob/master/FindTBB.cmake#L91 The idea is that the TBB build type will match your project build type. Also notice that if the debug build was not found, the release build is preferred. Similarly, the debug version is the fall back if the release build is not found.

The problem here is that it is difficult to predict what a user's preference will be. Each project is different. I provided `TBB_USE_DEBUG_BUILD` as a hook to override this behavior. _I.e._ you can force it to always pick the debug or release builds by setting the variable to 1 or 0, respectively. Or, you may use your own logic when setting this variable.

I am open to other suggestions, if you feel that this logic can be improved.

**Comment by caron** [comment]
Ok, so maybe I am using this wrong? I am using the cmake-gui locally and the cmd line on appveyor with the same behavior.

Here is my example on appveyor, I configure 'Release' and build 'Release'...

`cmake -G "%CMAKE_PLATFORM%" --config Release -DTBB_ROOT_DIR=c:/projects/openvdb/deps/tbb44_20160526oss ..
cmake --build . --config Release`

but I get a link error..

`LINK : fatal error LNK1104: cannot open file 'tbb.lib'`

If its set to config 'Release' shouldn't it find the non debug libraries?

For the cmake-gui since I am generating the Visual Studio solution all build types are created and so that line 91 you linked always chooses debug. Again, maybe my build system is designed poorly and doesn't adhere to some know standard?

**Comment by justusc** [comment]
I corrected an error in the way Release and Debug variables are handled. Please try the latest revision and let me know how it goes.

**Comment by caron** [comment]
It works now without having to add TBB_USE_DEBUG_BUILD=0. Thanks!

**Comment by justusc** [comment]
Great. Also I added some new output variables to help support multi configuration builds

**Comment by justusc** [comment]
The documentation is in the read me file.
